### ISSUE TITLE
The opencdms.org website is not easy to maintain or change.

### ISSUE THREAD

**Issue by Steve-Palmer** [opencdms/opencdms-project#10]
The http://www.opencdms.org/  website is currently hosted and managed outside the Github organisation. It could be moved to be hosted within Github, or elsewhere. Proposals need to be developed to ensure management and content reflects the project needs for public information.

**Comment by isedwards** [comment]
The current site uses the Drupal content management system making it fairly easy to maintain and change (we just need to request user accounts).

Changing the approach may be a longer term goal that can be proposed after demonstratable progress has been made?

Next steps are likely to be the circulation of the report from this week and seeking broad feedback on the approach that we are taking.

The OpenCDMS initiative is wider than just the creation of a unified open source solution, and there are many stakeholders, so this also needs to be considered.

In the meantime we should focus on the content that we need to share as a first priority.  If this is developed on GitHub then it can also be made available at https://opencdms.github.io/opencdms.org

**Comment by Steve-Palmer** [comment]
Discussion here of the content needs. Not just the text change identified yesterday, but links and existing documents. I have never used drupal (I have used typo3, Wordpress) but I guess I can  learn... Question on hosting was whether it made sense to move to Github (as discussed for climsoft.org).

**Comment by isedwards** [comment]
This issue, relating to the infrastructure and platform for the `opencdms.org` website, has now be replaced by the issue here: https://github.com/opencdms/sysadmin/issues/2
