### ISSUE TITLE
Draft Project Charter for OpenWIS Association AISBL

### ISSUE THREAD

**Issue by Steve-Palmer** [opencdms/opencdms-project#16]
Ownership needs to be established for the OpenCDMS project software. The [OpenWIS Association AISBL](http://openwis.github.io/openwis-documentation/) is set up for the same purpose for a closely-related project. The first step is to set up a Project Charter for OpenCDMS, agree it and then submit to the Board. 

Here is the first draft in Markdown format. Please add any comments, suggestions and edits under this Issue.

NOTE: The text below is an early version of the project charter that is no longer being updated. The most recent version is in the main repository [here](https://github.com/opencdms/opencdms-project/blob/master/charter/opencdms_charter.md)
-----------------------------
# Project Charter for _OpenCDMS_

## Aim

OpenCDMS is a free Reference Open Source Data Management System for atmospheric, hydrological, marine, phenological, composition and other environmental data with a time-series component. It stores observational data concerning water, weather, hydrology and climate in a secure and flexible manner and enables extracting useful information from the data.

OpenCDMS is intended to be used by the National Meteorological and Hydrological Services (NMHS) of WMO Members, and by any others wishing to use best-practices in managing and using these data. Best-practice is defined as management in compliance with the appropriate WMO manuals, especially the Guide to Climatological Practices ([WMO-100](https://public.wmo.int/en/resources/library/guide-climatological-practices-wmo-100))
the Climate Data Management System Specifications ([WMO-No 1131](https://library.wmo.int/doc_num.php?explnum_id=7867))
and the High Quality Global Data Management Framework for Climate ([HQ-GDMFC](http://meetings.wmo.int/cg-18/_layouts/15/WopiFrame.aspx?sourcedoc=/cg-18/English/2.%20PROVISIONAL%20REPORT%20(Approved%20documents)/Cg-18-d05-2(2)-CLIMATE-INFORMATION-SERVICES-ANNEX-approved_en.docx&amp;action=default)).

OpenCDMS is intended to be a practical toolset for implementing improved management and exchange of hydrological, climatological and other environmental observation data and metadata in response to WMO Resolutions, especially [WMO Cg-18 Resolution 22](http://www.wmo.int/pages/prog/wcp/wcdmp/dms/documents/Doc4-1_CongressResolution.pdf). As found by a [WMO survey](https://github.com/opencdms/opencdms-project/raw/master/wiki/et-drm/cdms_survey.pdf), there is a great need to improve the management and use of climate and hydrological data by the NMHSs, especially in developing countries.

OpenCDMS will also be complementary to other toolsets in the WMO Information System by enabling the long-term archiving and discovery of observation data and metadata as well as exchange of climatological and hydrological products and services.

## Scope

OpenCDMS is a phased project. The first phase is to build a community of contributors and developers with experience and interest in developing and using a CDMS, with an emphasis on including those based in developing countries. During this phase, a strategy for implementation will be developed, and the coding and implementation tools and standards will be investigated and agreed. An Application Programming Interface (API) will be developed which will wrap the database system for two (or more) of the candidate precursor CDMS (Climsoft and MCH).

In the second phase, a common data model for OpenCDMS will be developed and tested, using the API. User interface modules will be ported and tested with the OpenCDMS data model.

The third phase will concentrate on implementation and training, initially in the NMHSs using the precursor CDMS.

The OpenCDMS project will include modules providing specific data products to the WMO Information System, but assumes that WIS provides the interface to receive and transmit these products.

The OpenCDMS project will include porting of end-user hydrology and climate applications which are currently operational in the precursor systems (Climsoft and MCH) but will not include development of new end-user applications. It is assumed that these will be provided by the (separate) WMO Climate Services Toolbox project, or others.

## Deliverables

- Community of open-source contributors built
- Roadmap for OpenCDMS development and implementation
- API for environmental observation time-series data designed, tested and implemented
- OpenCDMS data model designed, tested an implemented.
- User interfaces for data and metadata management implemented
- End-user applications tested and implemented, with peer review.

## Sponsor and funding source

OpenCDMS is sponsored by WMO. WMO is providing limited funding for specific support activities, especially for project direction and mentoring of contributors. Other contributions are being provided in-kind, especially by contributors with previous experience in precursor CDMS systems. Further funding is expected to be provided by CDMS implementation projects where development of specific modules contributes to and benefits from the OpenCDMS project. No funding is required from the OpenWIS Association.

## Milestones &amp; Schedule

Phase 1 – to 31 December 2019:

- Roadmap for OpenCDMS development and implementation
- Workplan for developing the OpenCDMS data model
- Create and test an API for use with Climsoft, MCH (and later the OpenCDMS) databases.
- Identify and specify new user interface technologies for use in OpenCDMS.

Phase 2 – to 30 September 2020:

- Develop the data model for OpenCDMS
- Test the API with the OpenCDMS data model
- Implement existing user applications with the API and introduce to Climsoft and MCH releases.
- Training contributors and developers in the new user interface technologies.

Phase 3 – to 30 September 2021

- Implementation of the initial OpenCDMS package, with trial and evaluation.
- User training.

Later phases to be decided. These will expand the scope to functionality and data types which are recommended in WMO No-1131.

## Roles and Responsibilities

| **Resource Name** | **Organisation** | **Role** | **What this resource will be doing in relation to a listed milestone** | **Time period resource needed for** | ** ** |
| --- | --- | --- | --- | --- | --- |
|  Peer Hechler &amp; Nirina Ravalitera | WMO | Coordination | Secretariat and linkage to WMO Expert Team |  Continuing |   |
|  Marcellin Habimana | Climsoft Project | Coordination |  Project and Github management, link to Climsoft |  Continuing |   |
|  Ian Edwards | MyAcorn Ltd | Technical | Technical advice, training and community development |  Continuing |   |
| Dr David Stern | IDEMS International | Technical | Technical advice, training, student development, link to R-Instat | Continuing |   |
| Ms Etna Cervantes |   | Technical | Technical advice, link to MCH, hydrology applications | Continuing |   |
| Karen McCourt &amp; Steve Palmer | Met Office | Facilitation | Vision, project management, relationships. | Continuing |   |

## Communication and Reporting

The Steering Committee role is provided by reporting to the WMO Expert Team on Data Rescue and Management (or an appropriate successor Expert Team of WMO), with the Secretariat being provided by WMO.

The Technical Committee consists of stakeholders from WMO and the precursor CDMS project teams (initially Climsoft and MCH), along with experts and user representatives.

Users in the NMHSs will be encouraged to participate as Contributors, especially from their experience, and in the design, testing and usage discussions. There will be an emphasis on inclusion for contributors based in developing and least-developed countries.

## Configuration Management

Development and documentation will be managed through the Gihub project [https://github.com/opencdms](https://github.com/opencdms) as a free open-source project using best-practice and following the rules of the OpenWIS Association.

**Comment by mhabimana** [comment]
@Steve-Palmer -Thanks,the draft project Charter for the openCDMS looks great,well done!

**Comment by smachua** [comment]
@Steve-Palmer thanks for preparing the initial draft for OpenCDMS project. I am studying it and I will share few comments and inputs with the team soon.
However I, from Climsoft Project have a role in Technical advice, training and community development which am sure to contribute immensely. Hence I may be included in the table of Roles and Responsibilities.

**Comment by PeerWMO** [comment]
@Steve - Thanks Steve, fine with me! Only small typo in the table: Peer Hechler instead Hecler; Cheers; Peer.

**Comment by DenisStuber** [comment]
Well done.
I'll send my remarks by mails

**Comment by isedwards** [comment]
I've changed the table to correct Peer's name. I've also updated the text to add links for [WMO Cg-18 Resolution 22](http://www.wmo.int/pages/prog/wcp/wcdmp/dms/documents/Doc4-1_CongressResolution.pdf) and the [WMO survey](http://www.wmo.int/pages/prog/wcp/wcdmp/documents/analysis_questionnaire_CDMS.pdf) that Steve mentions.

I agree with adding Samuel to the roles and responsibilities table. He will have an essential role in helping to ensure that OpenCDMS is suitable for the Climsoft community. It would make sense to add  Eduardo as well.

@PeerWMO - make sure you use people's full usernames when you put the @ symbol infront... When you used `@Steve` in your message above, GitHub would have sent an email to [a different Steve](https://github.com/steve) (who has the username `@Steve`) instead of @Steve-Palmer (although Steve Palmer would also receive an email because he started this conversation).

**Comment by Steve-Palmer** [comment]
Here is the latest V5 version of the Charter (as docx - sorry failed to convert to markdown!)

[191127_OpenCDMS_ProjectCharter_V5.docx](https://github.com/opencdms/opencdms-project/files/3912979/191127_OpenCDMS_ProjectCharter_V5.docx)

**Comment by Steve-Palmer** [comment]
Ian has put the markdown version of the project charter online here:
https://github.com/opencdms/opencdms-project/blob/master/charter/opencdms_charter.md 

Please comment on this version rather than the Word one. Thanks!

**Comment by Steve-Palmer** [comment]
Version 6 of the Charter, incorporating suggestions from Peer and Denis. Thanks to Denis for textual changes in the pull request - I have added comments there. I will aim to produce a final version on Wednesday 11 Dec for submission to the OpenWIS Associstion Steering Group on Monday 16 Dec.
[191209_OpenCDMS_ProjectCharter_V6.docx](https://github.com/opencdms/opencdms-project/files/3941107/191209_OpenCDMS_ProjectCharter_V6.docx)

**Comment by Steve-Palmer** [comment]
Version 8 - hoping this is the final version (or very close). 

[191211_OpenCDMS_ProjectCharter_V8.docx](https://github.com/opencdms/opencdms-project/files/3952130/191211_OpenCDMS_ProjectCharter_V8.docx)

**Comment by mhabimana** [comment]
@Steve-Palmer: I went through the attached openCDMS Project Charter version 8 and found it ready for submission.

**Comment by Steve-Palmer** [comment]
Somer further updates - useful comments from William Wright. I have updated the Markdown version to this V9. Word version attached here:
[191211_OpenCDMS_ProjectCharter_V9.docx](https://github.com/opencdms/opencdms-project/files/3960964/191211_OpenCDMS_ProjectCharter_V9.docx)

**Comment by Steve-Palmer** [comment]
The proposals by Bruce Bannerman for an alternative project ownership and structure have now been published on the opencdms.org website (of which Bruce Bannerman currently has sole control, see [Issue 10](https://github.com/opencdms/opencdms-project/issues/10) ). This proposes that legal ownership of the IPR of the OpenCDMS project should be vested in an Australian not-for-profit company set up and controlled by Bruce Bannerman (as a self-employed entrepreneur) and NOT in the OpenWisAssociation AISBL (which was set up to perform this function for the OpenWIS Project). He very carefully does not make this explicit, but it is implicit in the documents, especially the diagram in the proposed [Governance document](https://www.opencdms.org/how-we-work/governance). 

In his proposal, he suggests a role for the OpenWIS Association AISBL which the OpenWIS Association is not capable of performing. Most of the rest of his proposal is not novel or controversial.

Please will members of the OpenCDMS community indicate if they support this alternative proposal or support continuing with vesting legal ownership of the OpenCDMS Project in the OpenWIS Association through the Project Charter, as already discussed.

**Comment by Steve-Palmer** [comment]
IMPORTANT: please will all members of the OpenCDMS community respond by 23:59 UTC on Wednesday 29/01/2020 with either:
**YES** - you support the formal request to the OpenWIS Association AISBL for adoption of the OpenCDMS Project Charter.
**NO** - you do not support the formal request to the OpenWIS Association, and you want another governance structure to be put in place.
Any Member not responding will be assumed to have no objection to the request to the OpenWIS Association.

**Comment by mhabimana** [comment]
**YES** - I support the formal request to the OpenWIS Association AISBL for adoption of the OpenCDMS Project Charter.

**Comment by PeerWMO** [comment]
Thanks Steve, YES; Peer.

**Comment by githubetna** [comment]
YES - I support the formal request to the OpenWIS Association for the adoption of the OpenCDMS. And thank you Steve for all your fine work.

-----
Etna CERVANTES
MCH programmer.

**Comment by githubetna** [comment]
> 
> 
> I've changed the table to correct Peer's name. I've also updated the text to add links for [WMO Cg-18 Resolution 22](http://www.wmo.int/pages/prog/wcp/wcdmp/dms/documents/Doc4-1_CongressResolution.pdf) and the [WMO survey](http://www.wmo.int/pages/prog/wcp/wcdmp/documents/analysis_questionnaire_CDMS.pdf) that Steve mentions.
> 
> I agree with adding Samuel to the roles and responsibilities table. He will have an essential role in helping to ensure that OpenCDMS is suitable for the Climsoft community. It would make sense to add Eduardo as well.
> 
> @PeerWMO - make sure you use people's full usernames when you put the @ symbol infront... When you used `@Steve` in your message above, GitHub would have sent an email to [a different Steve](https://github.com/steve) (who has the username `@Steve`) instead of @Steve-Palmer (although Steve Palmer would also receive an email because he started this conversation).

Hi Ian, thank you for your fine work. I agree with you that it would be necessary to add Eduardo in the  table. It can be used MCH as the organization message in the correspondent column. Thank you.

**Comment by volloholic** [comment]
Thanks all for the efforts on this. Yes I support the openvis application.

**Comment by dannyparsons** [comment]
This looks very sensible and useful. Yes, I support the application to OpenWIS.

@Steve-Palmer I made a small correction in the table to "IDEMS International" replacing "IDEMS Ltd". Thanks.

**Comment by smachua** [comment]
Yes, I support the request.

**Comment by isedwards** [comment]
When we revisit the OpenCDMS project charter this week, it may be worth looking at the charter of the OpenAPI Initiative for inspiration and comparison:

https://www.openapis.org/participate/how-to-contribute/governance

They have put a lot of effort into creating a level playing field and ensuring vendor-neutral solutions.

**Comment by isedwards** [comment]
What I like most about the [OpenAPI Charter](https://www.openapis.org/participate/how-to-contribute/governance) is that it makes no preemptive  technology decisions, it doesn't commit to any project deadlines, ... it concerns itself only with governance.

Here are their sections:
1. Mission of the OpenAPI Initiative
2. Membership
3. Business Governance Board
4. Technical Steering Committee (“TSC”)
5. Technical Oversight Board (“TOB”)
6. Core Values
7. IP Policy
8. Antitrust Guidelines
9. Budget
10. Linux Foundation General Rules and Operations
11. Amendments and Notice

Should our [Project Approach](https://github.com/opencdms/opencdms-project/blob/2efb7e8ce5581d9e1aeaa193b7f73a839bc9c38a/charter/opencdms_charter.md#project-approach), [Milestones](https://github.com/opencdms/opencdms-project/blob/2efb7e8ce5581d9e1aeaa193b7f73a839bc9c38a/charter/opencdms_charter.md#milestones--schedule) etc. instead be in a roadmap document that evolves regularly?

**Comment by PeerWMO** [comment]
Thanks Ian -good point. Such kind of framework can make it easy to accommodate the different bits and pieces of activities we do need to engage (ACP etc).

**Comment by isedwards** [comment]
I'm opposed to the idea of the OpenWIS Association having an obligation to manage finances for the project. This would create an administrative overhead with few, if any, benefits for the Association and other parties.

Separating financial involvement from ownership could also be a real advantage when attracting strategic partners.

**Comment by DenisStuber** [comment]
Could you remind me who is on the list "opencdms/opencdms-project". 

I did not say that the OpenWIS Association has an obligation to manage finances for the project. In general, it is better to have an independant treasurer that manages the budget.

I was talking about decisions and about budget transparency for the future OpenCDMS Committee (not OpenWIS). Decisions imply actions and actions imply human and financial resources. If you create an open source project you would have to say who are the decision-makers. And this has to be part of the project charter.

**Comment by isedwards** [comment]
@opencdms/opencdms-project is a publicly visible project at GitHub.

Anyone can view the discussion (including replies that are made by email). See #16 for this discussion. 

In addition, GitHub automatically emails everyone who has subscribed to "watch" the project (see the current list of watchers [here](https://github.com/opencdms/opencdms-project/watchers)). 

I think @Steve-Palmer suggested in yesterday's meeting that OpenWIS should administer finances. I actually don't remember whether anyone else commented on the suggestion.

In an open source project under OpenWIS we would also have the option to not have a budget and not have a treasurer.

Instead, funders could advertise opportunities and organisations/teams could reply to opportunities. 

The financial agreements would be between financier and supplier with OpenCDMS only deciding whether or not to accept collaborations (which result in accepting submissions of code/capabilities). There could be rules relating to this, e.g. transparency of funding could be required in order for contributions to be accepted.

As an open source project, if people don't like our rules there is the possibility they may fork the project and conduct the work they desire as a separate project that builds on our work.

Depending on the licence we choose, they may be required to share this work under the same license, in which case we would have the option to incorporate the work back into the main project (although this can be time consuming)

**Comment by Steve-Palmer** [comment]
@isedwards posted "suggested ... that OpenWIS _should_ administer finances" - that was a mishearing.I actually said "that OpenWIS Association _could_ administer finances if there are advantages". "could" is about possibility, not obligation. The example I gave is the the OpenWIS Association is a supplier providing programming to develop the OpenWIS product. Another example is that the Met Office made a donation to VideoLabs in order to facilitate a development we needed but they had not prioritised. So I do not want to exclude the possibility that money for OpenCDMS is routed through the OpenWIS Association, but we should not make that the only or main route.

**Comment by isedwards** [comment]
Thank you Steve, it looks like I completely misunderstood... what you propose is very sensible. 

I was concerned that the OpenWIS Association could be worried about extra administration duties we might imply.

**Comment by mhabimana** [comment]
@Steve-Palmer - Currently,the link pointing to the charter is under the overview page,to me it is somehow hidden since I struggled first to locate this. Can I suggest you to create a new page under the wiki page pointing directly to this document?

**Comment by isedwards** [comment]
@mhabimana - I've added a link to the charter on the [wiki homepage](https://github.com/opencdms/opencdms-project/wiki)

As soon as the final charter is agreed then it will move to the opencdms.org website

**Comment by mhabimana** [comment]
@isedwards - Perfect.

**Comment by Steve-Palmer** [comment]
Happy to report that the OpenWIS Association Steering Committee adopted the OpenCDMS Project at their meeting on 28/05/2020. We are now part of the Association, and we will now set up our governance to reflect this.
