### ISSUE TITLE
Name of the Project and software

### ISSUE THREAD

**Issue by nravalitera** [opencdms/opencdms-project#8]
Decide on an approach to address this issue (the "C" might be interpreted as not inclusive of hydrology or other environmental communities).

**Comment by Steve-Palmer** [comment]
Currently the website only references "Climate". I will contact Bruce to change the website. This will use the text ageed at the Expert Team meeting in December 2018.

(See section 5 of the [Final Report](https://ane4bf-datap1.s3-eu-west-1.amazonaws.com/wmocms/s3fs-public/ckeditor/files/ET-CDMS_FinalReportwithannexes.pdf) of the [Expert Meeting on WMO CDMS Strategy December 2018](https://public.wmo.int/en/events/meetings/expert-meeting-wmo-cdms-strategy))

>The meeting discussed aspects of replacing or not the word ‘Climate’ within Climate Data Management System (CDMS) to better reflect the usability of CDMSs for atmospheric, hydrological, marine and other environmental data with a time-series component. Eventually, it was suggested not to change the name CDMS and to explain in all communications that the phrase ‘climate’ is inclusive of hydrological, marine and other environmental data with a time-series component.

**Comment by isedwards** [comment]
I've changed the description of the OpenCDMS project ([here](https://github.com/opencdms/opencdms-project/)) to read:

> **OpenCDMS**
> **Climate and Hydrology Data Management System**
>
> OpenCDMS is a Reference Open Source Data Management System for atmospheric, hydrological, marine and other environmental data with a time-series component. It stores observational data concerning water, weather, hydrology and climate in a secure and flexible manner and enables extracting useful information from the data.
>
> OpenCDMS is intended to be used by the National Meteorological and Hydrological Services (NMHS) of WMO Members, and by any others wishing to use best-practices in managing and using these data.

The wording has been taken form the ET-CDMS Policy Statement (November 2015 Prague) and the Expert Meeting on WMO CDMS Strategy (December 2018 Geneva).

We also need to ensure that a complete definition is present in other places, including at [opencdms.org](http://www.opencdms.org) and in any further documentation produced by the Expert Team.  This is essential to ensure that the project is found by people searching for "hydrology data management system" and other search terms.

@opencdms/opencdms-project → Our joint efforts in this collaboration are in response to the "CDMS" Specifications that were created by the Expert Team on "CDMS". Their considered recommendation is to proceed with the name OpenCDMS and to clarify the meaning in full. If we do want to change the initials then we should approach them with a proposal. If we cannot reach an agreement with them then we will either need advice if we want to take this further, or we will need to proceed independently of their advice on this issue.

Please add your thoughts below - let's keep discussing this until we reach a solution that everyone is happy with.

**Comment by mhabimana** [comment]
@isedwards :Thanks,👍well done!

**Comment by Steve-Palmer** [comment]
Thanks, very good, "time-series component" is really key. Perhaps add the word "Phenology" and bring the Agro-met people on board as well; also "Atmospheric composition" (taken from the GAW home page).

**Comment by nravalitera** [comment]
And if we simply call it: Time-Series Database Management System (TS-DMS)?

**Comment by isedwards** [comment]
@githubetna @eporrasc - are you both still happy with the current name:

> **OpenCDMS**
> Climate and Hydrology Data Management System

I'm happy for us to choose anything else that can be agreed. My reasons for preferring "OpenCDMS" are:

- The name has been in use for ~5 years and is established
- The expert team (now called the "Expert Team on Data Rescue and Management") have revisited the name multiple times with the same eventual conclusion
- We are working to implement the CDMS Specifications
- We have acquired opencdms.org and other assets (like @opencdms on GitHub and twitter)
- As time passes it is becoming more difficult to change as it gets written into documentation and used in repository names etc.

**Comment by smachua** [comment]
I do agree with Ian. By using anything else other than OpenCDMS may appear like a different project from what others are focusing at.

**Comment by isedwards** [comment]
A charter has now been submitted to the OpenWIS Association using OpenCDMS as the name of the project
